### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by Zak777** [LambdaBooks/understandinges6ua#87]
1. Глава 4, підрозділ: Розширення синтаксису об’єктного літерала(2-ге речення)
_Маємо:_
Об’єктний літерал став таким популярним задяки...
_Потрібно:_
Об’єктний літерал став таким популярним **завдяки**...

2. Глава 4, підрозділ: Скорочення ініціалізації властивостей(Останній абзац, останнє речення)
_Маємо:_
Присвоєння властивості локальної змінної з таким же самим ім’ям є дуже поширеним патерному у JavaScript...
_Потрібно:_
Присвоєння властивості локальної змінної з таким же самим ім’ям є дуже поширеним **патерном** у JavaScript...

3. Глава 4, підрозділ: Зміна прототипу об’єкта(3-й абзац, останнє речення) (помилка в англомовному варіанті - в оригіналі)
_Маємо:_
Коли прототипом стає об’єкт dog, person.getGreeting() виводить "Woof" тому, що початкове відношення з person було розірване.
_Потрібно:_
Коли прототипом стає об’єкт dog, **friend**.getGreeting() виводить "Woof" тому, що початкове відношення з person було розірване.
_Пояснення:_
person.getGreeting() виводить "Hello".

4. Глава 5, підрозділ: Деструктурування вкладених об’єктів (4й абзац, 2ге речення)
_Маємо:_
Шаблон деструктурування може мати довільний рівень вкладненості...
_Потрібно:_
Шаблон деструктурування може мати довільний рівень **вкладеності**...

**Comment by denysdovhan** [comment]
Thanks for contributing!
